# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Install cmake
    - name: get-cmake
      uses: lukka/get-cmake@v3.17.1

    # Install LLVM + boehm gc
    - name: Install LLVM, libgc
      run: sudo apt install llvm-10 llvm-10-dev libgc-dev
      
    # Build and test cmake project
    - name: Build
      run: mkdir build && cd build && cmake -DENABLE_TESTING=ON .. && cmake --build . && sudo cmake --install .
      working-directory: ${{ runner.workspace }}/ovid

    - name: Ovidc Test Framework
      run: cd build && ./runUnitTests && OVIDC_TESTSUITE_PATH=`pwd`/../tests ./runTests
      working-directory: ${{ runner.workspace }}/ovid